version: "3"
services:
  meilisearch:
    image: "getmeili/meilisearch:latest"
    ports:
      - "7700:7700"
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_NO_SENTRY=true
      - MEILI_MASTER_KEY=test_api_key_very_secure
